/**
 * @carbid/tokens — platform-agnostic design tokens.
 *
 * Web consumes these as CSS custom properties (generated by `pnpm --filter @carbid/tokens build:css`).
 * React Native consumes the TypeScript objects directly, because RN has no CSS variables.
 */

export * from './colors';
export * from './typography';
export * from './layout';

import { semanticColors, type ThemeName } from './colors';

/* ------------------------------------------------------------------ *
 * Colour-space helpers
 *
 * shadcn/ui components rely on opacity modifiers (`bg-primary/90`, `border-border/50`). Those only
 * work when the CSS variable holds an HSL *channel triplet* — `221 85% 50%` — so Tailwind can
 * compose `hsl(var(--primary) / <alpha-value>)`. Storing hex in the variable silently breaks every
 * `/opacity` utility, which is why this conversion exists.
 * ------------------------------------------------------------------ */

/** `#135bec` → `221 85% 50%` (space-separated channels, no `hsl()` wrapper). */
export function hexToHslChannels(hex: string): string {
  const m = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex.trim());
  if (!m) throw new Error(`hexToHslChannels: expected 6-digit hex, received "${hex}"`);

  const r = parseInt(m[1], 16) / 255;
  const g = parseInt(m[2], 16) / 255;
  const b = parseInt(m[3], 16) / 255;

  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const l = (max + min) / 2;
  const d = max - min;

  let h = 0;
  let s = 0;
  if (d !== 0) {
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r:
        h = ((g - b) / d + (g < b ? 6 : 0)) / 6;
        break;
      case g:
        h = ((b - r) / d + 2) / 6;
        break;
      default:
        h = ((r - g) / d + 4) / 6;
    }
  }

  const round = (n: number) => Math.round(n * 10) / 10;
  return `${round(h * 360)} ${round(s * 100)}% ${round(l * 100)}%`;
}

/** Values already in `rgba(...)` form are passed through untouched. */
function toCssValue(value: string): string {
  return value.startsWith('#') ? hexToHslChannels(value) : value;
}

const KEBAB = (key: string) => key.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

/** Emits the `--role: H S% L%;` declarations for one theme. */
export function cssVariablesFor(theme: ThemeName): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [role, value] of Object.entries(semanticColors[theme])) {
    out[`--${KEBAB(role)}`] = toCssValue(value as string);
  }
  return out;
}

/**
 * The theme object React Native consumes. Hex is kept verbatim here — RN's StyleSheet accepts hex
 * directly and gains nothing from HSL channels.
 */
export function nativeTheme(theme: ThemeName) {
  return semanticColors[theme];
}
